### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by bile0026** [javadmohebbi/nfCollector#12]
Issue:
nfcol service is crashing. Also, doesn't seem to be populating InfluxDB with data. 

Info:
OS: CentOS 8
InfluxDB: Version 1.8.0
Netflow Version: 9
Netflow Device manufacture: PaloAlto

nfc.yaml file:
```
# # # # # # # # # # # # # # # # # #
#       Netflow Collector         #
#         Configuration           #
# # # # # # # # # # # # # # # # # #
server:
  # Listen Address
  address: 0.0.0.0

  # Listen UDP Port
  port: 2055

  # If true, nfc will write flow data into stdout
  dump: false

  # Activate forwarder
  forwarder: true

  # Host to forward - Can be separated by ; (semi-colon) eg: 127.0.0.1;192.168.100.1
  forwarderHost: 127.0.0.1

  # Forwarder UDP Port
  forwarderPort: 7161

# # # # # # # # # # # # # # # # # #
#    IP2Location Configuration    #
# # # # # # # # # # # # # # # # # #
ip2location:
  # IP2Location command path
  # cmd: /usr/local/bin/ip2location
  cmd: /etc/ip2location/ip2location

  # Path to Local GEO Database. Read more at:
  #      https://github.com/javadmohebbi/IP2Location#local-database-format
  local: /etc/ip2location/local.csv

# # # # # # # # # # # # # # # # # #
#     Exporter Configuration      #
# # # # # # # # # # # # # # # # # #
exporter:
  # Enable if it's true
  enable: true

  # Currently Only InfluxDB (1.x) supported
  type: influxdb


# # # # # # # # # # # # # # # # # #
#     InfluxDB Configuration      #
# # # # # # # # # # # # # # # # # #
influxDB:
  # InfluxDB Host
  host: 127.0.0.1

  # InfluxDB Port
  port: 8086

  # InfluxDB Username. Can be null
  username:  <username>

  # InfluxDB Password. Can be null
  password: <password>

  # InfluxDB Database
  # InfluxDB command example for creating database:
  #       CREATE DATABASE "netflowDB" WITH DURATION 10d REPLICATION 1 SHARD DURATION 1h NAME "nfc"
  database: netflowDB

  # Temp Dir for InfluxDB Metrics. MUST be ended with / (Linux) or \ (Windows)
  tmpDir: /tmp/nfcol/


# # # # # # # # # # # # # # # # # #
#          Measurements           #
# # # # # # # # # # # # # # # # # #
measurements:
  # Netflow Summary Measurement Name
  summaryProto: sum_proto

  # Netflow GEO Summary Measurement Name
  summaryProtoGeo: sum_proto_geo

```

nfcol.service file
```
[Unit]
Description = Netflow Collector Service
After = network.target influxd.service

[Service]
ExecStart = /etc/nfcol/nfcol

[Install]
WantedBy = multi-user.target

```

syslog output:
```
nfcol[2442]: 2020/07/07 18:07:05 decoder error: EOF
nfcol[2442]: 2020/07/07 18:07:04 decoder error: EOF
nfcol[2442]: 2020/07/07 18:07:05 Export job configs to send metrics to InfluxDB: 127.0.0.1:8086 (Database: netflowDB)
nfcol[2442]: 2020/07/07 18:07:05 Job for measurement (sum_proto) Started!
nfcol[2442]: 2020/07/07 18:07:05 Deleting .done extension & rewrite suspended .working files in directory:  /tmp/nfcol/sum_proto/
nfcol[2442]: 2020/07/07 18:07:05 File nfc-20200707-18-05-(sum_proto).metrics.working.done deteled
nfcol[2442]: 2020/07/07 18:07:05 Job for measurement (sum_proto_geo) Started!
nfcol[2442]: 2020/07/07 18:07:05 Deleting .done extension & rewrite suspended .working files in directory:  /tmp/nfcol/sum_proto_geo/
nfcol[2442]: 2020/07/07 18:07:05 File nfc-20200707-18-05-(sum_proto_geo).metrics.working.done deteled
nfcol[2442]: 2020/07/07 18:07:07 Reading directory /tmp/nfcol/sum_proto_geo/
nfcol[2442]: 2020/07/07 18:07:07 Reading metrics nfc-20200707-18-06-(sum_proto_geo).metrics
nfcol[2442]: 2020/07/07 18:07:07 Reading directory /tmp/nfcol/sum_proto/
nfcol[2442]: 2020/07/07 18:07:07 Reading metrics nfc-20200707-18-06-(sum_proto).metrics
nfcol[2442]: 2020/07/07 18:07:07 decoder error: EOF
influxd[1218]: [httpd] 127.0.0.1 - nfcol [07/Jul/2020:18:07:08 -0400] "POST /write?consistency=&db=netflowDB&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 3306c429-c09e-11ea-8017-005056834c64 242148
influxd[1218]: [httpd] 127.0.0.1 - nfcol [07/Jul/2020:18:07:08 -0400] "POST /write?consistency=&db=netflowDB&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 333ecab5-c09e-11ea-8018-005056834c64 143852
nfcol[2442]: 2020/07/07 18:07:08 Adding .done extension to .metrics in directory:  /tmp/nfcol/sum_proto/
nfcol[2442]: 2020/07/07 18:07:08 File nfc-20200707-18-06-(sum_proto).metrics.working renamed to nfc-20200707-18-06-(sum_proto).metrics.working.done
nfcol[2442]: 2020/07/07 18:07:08 Job for measurement (sum_proto) Finished!
nfcol[2442]: 2020/07/07 18:07:10 Adding .done extension to .metrics in directory:  /tmp/nfcol/sum_proto_geo/
nfcol[2442]: 2020/07/07 18:07:10 File nfc-20200707-18-06-(sum_proto_geo).metrics.working renamed to nfc-20200707-18-06-(sum_proto_geo).metrics.working.done
nfcol[2442]: 2020/07/07 18:07:10 Job for measurement (sum_proto_geo) Finished!
nfcol[2442]: 2020/07/07 18:07:11 decoder error: EOF
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  pipe2: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  pipe2: too many open files
 nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /dev/null: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 IP2Location Error:  open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 Error reading config file, open /etc/nfcol/nfc.yaml: too many open files
nfcol[2442]: 2020/07/07 18:07:14 open /etc/nfcol/nfc.yaml: too many open files
systemd[1]: nfcol.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: nfcol.service: Failed with result 'exit-code'.
```
